In [3]:
import pickle


with open('C:/Users/thale/Python/Avaliação dos algoritmos/Tunning dos valores/credit.pkl' ,'rb') as f :
    x_credit_treinamento,y_credit_treinamento,x_credit_teste,y_credit_teste=pickle.load(f)

In [4]:
import numpy as np


x_credit=np.concatenate((x_credit_treinamento,x_credit_teste), axis=0)
y_credit=np.concatenate((y_credit_treinamento,y_credit_teste), axis=0)

In [4]:
x_credit.shape,y_credit.shape

((2000, 3), (2000,))

In [5]:
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC

In [7]:
classificador_rede_neural=MLPClassifier(activation='relu',batch_size=56,solver='adam')
classificador_rede_neural.fit(x_credit,y_credit)

c:\Users\thale\Python\env\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(batch_size=56)

In [8]:
classaficador_arvore=DecisionTreeClassifier(criterion='entropy',min_samples_leaf=1,min_samples_split=5,splitter='best')
classaficador_arvore.fit(x_credit,y_credit)

DecisionTreeClassifier(criterion='entropy', min_samples_split=5)

In [39]:
classaficador_svm=SVC(C=2.0,kernel='rbf',probability=True)
classaficador_svm.fit(x_credit,y_credit)

SVC(C=2.0, probability=True)

In [40]:
import pickle
pickle.dump(classificador_rede_neural,open('rede_neural_finalizado.sav','wb'))
pickle.dump(classaficador_arvore ,open('arvore_finalizado.sav','wb'))
pickle.dump(classaficador_svm,open('svm_finalizado.sav','wb'))

# CARREGAR CLASSAFICADOR JA TREINADO

In [41]:
rede_neural=pickle.load(open('rede_neural_finalizado.sav','rb'))
arvore=pickle.load(open('arvore_finalizado.sav','rb'))
svm=pickle.load(open('svm_finalizado.sav','rb'))

In [25]:
novo_registro=x_credit[1999]
novo_registro

array([-1.03572293, -0.93978122,  0.04244312])

In [26]:
novo_registro.shape

(3,)

In [27]:
novo_registro=novo_registro.reshape(1,-1)
novo_registro.shape

(1, 3)

In [28]:
rede_neural.predict(novo_registro)


array([1], dtype=int64)

In [29]:
arvore.predict(novo_registro)

array([1], dtype=int64)

In [30]:
svm.predict(novo_registro)

array([1], dtype=int64)

# **Combinação de classificadores**

In [22]:
novo_registro=x_credit[1999]
novo_registro=novo_registro.reshape(1,-1)
novo_registro,novo_registro.shape

(array([[-1.03572293, -0.93978122,  0.04244312]]), (1, 3))

In [23]:
resposta_rede_neural=rede_neural.predict(novo_registro)
resposta_arvore=arvore.predict(novo_registro)
resposta_svm=svm.predict(novo_registro)

In [24]:
resposta_rede_neural[0],resposta_arvore[0],resposta_svm[0]

(1, 1, 1)

In [25]:
paga=0
não_paga=0

if resposta_rede_neural[0] ==1:
    não_paga +=1
else:
    paga+=1
if resposta_arvore[0] ==1:
    não_paga +=1
else:
    paga +=1

if resposta_svm[0] ==1:
    não_paga +=1
else:
    paga+=1    


if paga > não_paga:
    print("cliente pagarar o empresto")
elif paga == não_paga:
    print("EMPATE")
else:
    print("cliente não pagarar o emprestimo ")    

cliente não pagarar o emprestimo 


# Rejeição de classificadores

# em apilicações reais

º aponta uma unica hipotese

º rejeita o resultado se não tiver certeza suficiente

In [44]:
novo_registro = x_credit[1999]
novo_registro = novo_registro.reshape(1, -1)
novo_registro, novo_registro.shape

(array([[-1.03572293, -0.93978122,  0.04244312]]), (1, 3))

In [45]:
resposta_rede_neural = rede_neural.predict(novo_registro)
resposta_arvore = arvore.predict(novo_registro)
resposta_svm = svm.predict(novo_registro)

In [46]:
resposta_rede_neural[0], resposta_arvore[0],resposta_svm[0]

(1, 1, 1)

In [47]:
propabilidade_rede_neural=rede_neural.predict_proba(novo_registro)
propabilidade_rede_neural


array([[8.64385345e-05, 9.99913561e-01]])

In [49]:
confiaça_rede_neural=propabilidade_rede_neural.max()
confiaça_rede_neural

0.9999135614655033

In [50]:
propabilidade_arvore=arvore.predict_log_proba(novo_registro)
confiaça_arvore = propabilidade_arvore.max()
confiaça_arvore

c:\Users\thale\Python\env\Lib\site-packages\sklearn\tree\_classes.py:1035: RuntimeWarning: divide by zero encountered in log
  return np.log(proba)


0.0

In [51]:
propabilidade_svm=svm.predict_log_proba(novo_registro)
confiaça_svm = propabilidade_svm.max()
confiaça_svm

-0.009167189128447363

In [53]:
paga = 0
não_paga = 0
confiança_minima=0.999999
algortimo=0

if confiaça_rede_neural >= confiança_minima:
   algortimo +=1
    

   if resposta_rede_neural[0] == 1:
    não_paga += 1
   else:
    paga += 1
if confiaça_arvore >= confiança_minima:
  algortimo +=1

  if resposta_arvore[0] == 1:
    não_paga += 1
  else:
    paga += 1

if confiaça_svm >= confiança_minima:
  algortimo +=1
  if resposta_svm[0] == 1:
    não_paga += 1
  else:
    paga += 1


if paga > não_paga:
    print(f"cliente pagarar o empresto,baseado em  algortimos :{algortimo}")
elif paga == não_paga:
    print(f"EMPATE, baseado em algortimos:{algortimo}")
else:
    print(f"cliente não pagarar o emprestimo,baseado em algortimos : {algortimo} ")

EMPATE, baseado em algortimos:0
