# **REGRESSÃO POLINOMIAL**


# Base de dados plano de saude

In [6]:
import pandas as pd


base_plano_polinomial=pd.read_csv('C:/Users/thale/Python/regressao polinomial/plano_saude2.csv')
base_plano_polinomial

idade  custo
0     18    470
1     23    520
2     28    630
3     33    830
4     38   1150
5     43   1530
6     48   2040
7     53   3080
8     58   5100
9     63  10100

In [7]:
x_plano_saude2=base_plano_polinomial.iloc[:,0:1].values
y_plano_saude2=base_plano_polinomial.iloc[:,1].values


In [8]:
x_plano_saude2

array([[18],
       [23],
       [28],
       [33],
       [38],
       [43],
       [48],
       [53],
       [58],
       [63]], dtype=int64)

In [9]:
y_plano_saude2

array([  470,   520,   630,   830,  1150,  1530,  2040,  3080,  5100,
       10100], dtype=int64)

In [10]:
from sklearn.preprocessing import PolynomialFeatures
poly=PolynomialFeatures(degree=4)
x_plano_saude2_poly=poly.fit_transform(x_plano_saude2)

In [11]:
x_plano_saude2_poly.shape

(10, 5)

In [12]:
x_plano_saude2_poly

array([[1.0000000e+00, 1.8000000e+01, 3.2400000e+02, 5.8320000e+03,
        1.0497600e+05],
       [1.0000000e+00, 2.3000000e+01, 5.2900000e+02, 1.2167000e+04,
        2.7984100e+05],
       [1.0000000e+00, 2.8000000e+01, 7.8400000e+02, 2.1952000e+04,
        6.1465600e+05],
       [1.0000000e+00, 3.3000000e+01, 1.0890000e+03, 3.5937000e+04,
        1.1859210e+06],
       [1.0000000e+00, 3.8000000e+01, 1.4440000e+03, 5.4872000e+04,
        2.0851360e+06],
       [1.0000000e+00, 4.3000000e+01, 1.8490000e+03, 7.9507000e+04,
        3.4188010e+06],
       [1.0000000e+00, 4.8000000e+01, 2.3040000e+03, 1.1059200e+05,
        5.3084160e+06],
       [1.0000000e+00, 5.3000000e+01, 2.8090000e+03, 1.4887700e+05,
        7.8904810e+06],
       [1.0000000e+00, 5.8000000e+01, 3.3640000e+03, 1.9511200e+05,
        1.1316496e+07],
       [1.0000000e+00, 6.3000000e+01, 3.9690000e+03, 2.5004700e+05,
        1.5752961e+07]])

In [13]:


from sklearn.linear_model import LinearRegression


regressor_saude_polinomial=LinearRegression()
regressor_saude_polinomial.fit(x_plano_saude2_poly,y_plano_saude2)

LinearRegression()

In [14]:
#paramentro #B0
regressor_saude_polinomial.intercept_

16561.974608174714

In [15]:
#paramentro #b1
regressor_saude_polinomial.coef_

array([ 0.00000000e+00, -2.12242252e+03,  9.90404198e+01, -1.95058275e+00,
        1.40792541e-02])

In [16]:
novo=[[40]]

In [17]:
novo=poly.transform(novo)
novo

array([[1.00e+00, 4.00e+01, 1.60e+03, 6.40e+04, 2.56e+06]])

In [18]:
regressor_saude_polinomial.predict(novo)

array([1335.33958098])

In [19]:
previsoes=regressor_saude_polinomial.predict(x_plano_saude2_poly)
previsoes

array([ 549.65035639,  345.85081888,  616.53846302,  975.83916183,
       1249.06759979, 1472.72727289, 1894.51048857, 2973.29836578,
       5379.16083493, 9993.35663792])

In [20]:
import plotly.express as px

grafico2 = px.scatter(x=x_plano_saude2[:,0], y=y_plano_saude2)
grafico2 . add_scatter(x=x_plano_saude2[:,0], y=previsoes , name='Regressão')
grafico2.show()

# Base preço das casas

In [21]:
base_casas = pd.read_csv(
    'C:/Users/thale/Python/regressão parte2/house_prices.csv')
base_casas

id             date     price  bedrooms  bathrooms  \
0      7129300520  20141013T000000  221900.0         3       1.00   
1      6414100192  20141209T000000  538000.0         3       2.25   
2      5631500400  20150225T000000  180000.0         2       1.00   
3      2487200875  20141209T000000  604000.0         4       3.00   
4      1954400510  20150218T000000  510000.0         3       2.00   
...           ...              ...       ...       ...        ...   
21608   263000018  20140521T000000  360000.0         3       2.50   
21609  6600060120  20150223T000000  400000.0         4       2.50   
21610  1523300141  20140623T000000  402101.0         2       0.75   
21611   291310100  20150116T000000  400000.0         3       2.50   
21612  1523300157  20141015T000000  325000.0         2       0.75   

       sqft_living  sqft_lot  floors  waterfront  view  ...  grade  \
0             1180      5650     1.0           0     0  ...      7   
1             2570      7242     2.0           0     0  ...      7   
2              770     10000     1.0           0     0  ...      6   
3             1960      5000     1.0           0     0  ...      7   
4             1680      8080     1.0           0     0  ...      8   
...            ...       ...     ...         ...   ...  ...    ...   
21608         1530      1131     3.0           0     0  ...      8   
21609         2310      5813     2.0           0     0  ...      8   
21610         1020      1350     2.0           0     0  ...      7   
21611         1600      2388     2.0           0     0  ...      8   
21612         1020      1076     2.0           0     0  ...      7   

       sqft_above  sqft_basement  yr_built  yr_renovated  zipcode      lat  \
0            1180              0      1955             0    98178  47.5112   
1            2170            400      1951          1991    98125  47.7210   
2             770              0      1933             0    98028  47.7379   
3            1050            910      1965             0    98136  47.5208   
4            1680              0      1987             0    98074  47.6168   
...           ...            ...       ...           ...      ...      ...   
21608        1530              0      2009             0    98103  47.6993   
21609        2310              0      2014             0    98146  47.5107   
21610        1020              0      2009             0    98144  47.5944   
21611        1600              0      2004             0    98027  47.5345   
21612        1020              0      2008             0    98144  47.5941   

          long  sqft_living15  sqft_lot15  
0     -122.257           1340        5650  
1     -122.319           1690        7639  
2     -122.233           2720        8062  
3     -122.393           1360        5000  
4     -122.045           1800        7503  
...        ...            ...         ...  
21608 -122.346           1530        1509  
21609 -122.362           1830        7200  
21610 -122.299           1020        2007  
21611 -122.069           1410        1287  
21612 -122.299           1020        1357  

[21613 rows x 21 columns]

In [22]:
x_casas = base_casas.iloc[:, 5:6].values
x_casas

array([[1180],
       [2570],
       [ 770],
       ...,
       [1020],
       [1600],
       [1020]], dtype=int64)

In [23]:
y_casas = base_casas.iloc[:, 2].values
y_casas

array([221900., 538000., 180000., ..., 402101., 400000., 325000.])

In [24]:
from sklearn.model_selection import train_test_split
x_casas_treinamento,x_casas_teste,y_casas_treinamento,y_casas_teste = train_test_split(x_casas,y_casas , test_size=0.3, random_state=0)

In [25]:
x_casas_treinamento.shape

(15129, 1)

In [26]:
x_casas_teste.shape

(6484, 1)

In [27]:
from sklearn.preprocessing import PolynomialFeatures
poly=PolynomialFeatures(degree=2)
x_casas_treinamento_poly=poly.fit_transform(x_casas_treinamento)
x_casas_teste_poly=poly.fit_transform(x_casas_teste)

In [28]:
x_casas_treinamento.shape,x_casas_teste_poly.shape

((15129, 1), (6484, 3))

In [29]:
regressor_casa_polinomial=LinearRegression()
regressor_casa_polinomial.fit(x_casas_treinamento_poly,y_casas_treinamento)


LinearRegression()

In [30]:
regressor_casa_polinomial.score(x_casas_treinamento_poly,y_casas_treinamento)

0.5266754365257983

In [31]:
regressor_casa_polinomial.score(x_casas_teste_poly, y_casas_teste)

0.5440119730889539

In [32]:
previsoes=regressor_casa_polinomial.predict(x_casas_teste_poly)
previsoes

array([ 375566.90351566, 1338412.22761335,  377457.94420405, ...,
        528825.73264338,  385089.0236226 ,  355207.10593201])

In [33]:
y_casas_teste

array([ 297000., 1578000.,  562100., ...,  380000.,  268000.,  206000.])

In [34]:
from sklearn.metrics import mean_absolute_error


mean_absolute_error(y_casas_teste,previsoes)

165884.0129398659

# Regressão com Arvore de decissão

In [35]:
x_plano_saude2

array([[18],
       [23],
       [28],
       [33],
       [38],
       [43],
       [48],
       [53],
       [58],
       [63]], dtype=int64)

In [36]:
y_plano_saude2

array([  470,   520,   630,   830,  1150,  1530,  2040,  3080,  5100,
       10100], dtype=int64)

In [37]:
from sklearn.tree import DecisionTreeRegressor
regresspr_arvore_saude=DecisionTreeRegressor()
regresspr_arvore_saude.fit(x_plano_saude2,y_plano_saude2)

DecisionTreeRegressor()

In [38]:
previsoes=regresspr_arvore_saude.predict(x_plano_saude2)
previsoes

array([  470.,   520.,   630.,   830.,  1150.,  1530.,  2040.,  3080.,
        5100., 10100.])

In [39]:
y_plano_saude2

array([  470,   520,   630,   830,  1150,  1530,  2040,  3080,  5100,
       10100], dtype=int64)

In [40]:
regresspr_arvore_saude.score(x_plano_saude2,y_plano_saude2)


1.0

In [41]:


grafico2 = px.scatter(x=x_plano_saude2.ravel(), y=y_plano_saude2)
grafico2 . add_scatter(x=x_plano_saude2.ravel(), y=previsoes, name='Regressão')
grafico2.show()

In [42]:
import numpy as np


x_teste_arvore=np.arange(min(x_plano_saude2),max(x_plano_saude2),0.1)
x_teste_arvore

C:\Users\thale\AppData\Local\Temp\ipykernel_7068\3525640104.py:4: DeprecationWarning:

Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)



array([18. , 18.1, 18.2, 18.3, 18.4, 18.5, 18.6, 18.7, 18.8, 18.9, 19. ,
       19.1, 19.2, 19.3, 19.4, 19.5, 19.6, 19.7, 19.8, 19.9, 20. , 20.1,
       20.2, 20.3, 20.4, 20.5, 20.6, 20.7, 20.8, 20.9, 21. , 21.1, 21.2,
       21.3, 21.4, 21.5, 21.6, 21.7, 21.8, 21.9, 22. , 22.1, 22.2, 22.3,
       22.4, 22.5, 22.6, 22.7, 22.8, 22.9, 23. , 23.1, 23.2, 23.3, 23.4,
       23.5, 23.6, 23.7, 23.8, 23.9, 24. , 24.1, 24.2, 24.3, 24.4, 24.5,
       24.6, 24.7, 24.8, 24.9, 25. , 25.1, 25.2, 25.3, 25.4, 25.5, 25.6,
       25.7, 25.8, 25.9, 26. , 26.1, 26.2, 26.3, 26.4, 26.5, 26.6, 26.7,
       26.8, 26.9, 27. , 27.1, 27.2, 27.3, 27.4, 27.5, 27.6, 27.7, 27.8,
       27.9, 28. , 28.1, 28.2, 28.3, 28.4, 28.5, 28.6, 28.7, 28.8, 28.9,
       29. , 29.1, 29.2, 29.3, 29.4, 29.5, 29.6, 29.7, 29.8, 29.9, 30. ,
       30.1, 30.2, 30.3, 30.4, 30.5, 30.6, 30.7, 30.8, 30.9, 31. , 31.1,
       31.2, 31.3, 31.4, 31.5, 31.6, 31.7, 31.8, 31.9, 32. , 32.1, 32.2,
       32.3, 32.4, 32.5, 32.6, 32.7, 32.8, 32.9, 33

In [43]:
x_teste_arvore.shape

(450,)

In [44]:
x_teste_arvore=x_teste_arvore.reshape(-1,1)
x_teste_arvore.shape

(450, 1)

In [45]:


grafico2 = px.scatter(x=x_plano_saude2.ravel(), y=y_plano_saude2)
grafico2 . add_scatter(x=x_teste_arvore.ravel(), y=regresspr_arvore_saude.predict(x_teste_arvore), name='Regressão')
grafico2.show()

In [101]:
regresspr_arvore_saude.predict([[10]])

array([470.])

# Base preço casa

In [53]:
x_casas_treinamento.shape

(15129, 1)

In [54]:
x_casas_treinamento

array([[1390],
       [1450],
       [2860],
       ...,
       [2360],
       [2370],
       [2380]], dtype=int64)

In [55]:
y_casas_treinamento

array([400000., 430000., 720000., ..., 431000., 411000., 699900.])

In [56]:
x_casas_teste.shape

(6484, 1)

In [57]:
regressor_arvore_casa=DecisionTreeRegressor()
regressor_arvore_casa.fit(x_casas_treinamento,y_casas_treinamento)



DecisionTreeRegressor()

In [58]:
regressor_arvore_casa.score(x_casas_treinamento,y_casas_treinamento)

0.6333418801272528

In [59]:
regressor_arvore_casa.score(x_casas_teste,y_casas_teste)

0.4938582480846785

In [60]:
previsoes=regressor_arvore_casa.predict(x_casas_teste)
previsoes

array([ 371652.48148148, 1119000.        ,  367642.        , ...,
        509418.78      ,  430163.03571429,  368505.30588235])

In [61]:
y_casas_teste

array([ 297000., 1578000.,  562100., ...,  380000.,  268000.,  206000.])

In [62]:

mean_absolute_error(y_casas_teste, previsoes)

169479.06589217673

# **RANDOM FOREST COM REGRESSAO**

In [63]:
x_plano_saude2

array([[18],
       [23],
       [28],
       [33],
       [38],
       [43],
       [48],
       [53],
       [58],
       [63]], dtype=int64)

In [64]:
y_plano_saude2

array([  470,   520,   630,   830,  1150,  1530,  2040,  3080,  5100,
       10100], dtype=int64)

In [90]:
from sklearn.ensemble import RandomForestRegressor
regressor_random_fores_saude=RandomForestRegressor(n_estimators=25)
regressor_random_fores_saude.fit(x_plano_saude2,y_plano_saude2)

RandomForestRegressor(n_estimators=25)

In [91]:
regressor_random_fores_saude.score(x_plano_saude2,y_plano_saude2)

0.9905348049173193

In [92]:
x_teste_arvore

array([[18. ],
       [18.1],
       [18.2],
       [18.3],
       [18.4],
       [18.5],
       [18.6],
       [18.7],
       [18.8],
       [18.9],
       [19. ],
       [19.1],
       [19.2],
       [19.3],
       [19.4],
       [19.5],
       [19.6],
       [19.7],
       [19.8],
       [19.9],
       [20. ],
       [20.1],
       [20.2],
       [20.3],
       [20.4],
       [20.5],
       [20.6],
       [20.7],
       [20.8],
       [20.9],
       [21. ],
       [21.1],
       [21.2],
       [21.3],
       [21.4],
       [21.5],
       [21.6],
       [21.7],
       [21.8],
       [21.9],
       [22. ],
       [22.1],
       [22.2],
       [22.3],
       [22.4],
       [22.5],
       [22.6],
       [22.7],
       [22.8],
       [22.9],
       [23. ],
       [23.1],
       [23.2],
       [23.3],
       [23.4],
       [23.5],
       [23.6],
       [23.7],
       [23.8],
       [23.9],
       [24. ],
       [24.1],
       [24.2],
       [24.3],
       [24.4],
       [24.5],
       [24

In [93]:

grafico2 = px.scatter(x=x_plano_saude2.ravel(), y=y_plano_saude2)
grafico2 . add_scatter(x=x_teste_arvore.ravel(
), y=regressor_random_fores_saude.predict(x_teste_arvore), name='Regressão')
grafico2.show()

In [99]:
regressor_random_fores_saude.predict([[12]])

array([523.6])

# Base com preço das casas

In [125]:
x_casas_treinamento.shape

(15129, 1)

In [126]:
x_casas_treinamento

array([[1390],
       [1450],
       [2860],
       ...,
       [2360],
       [2370],
       [2380]], dtype=int64)

In [127]:
y_casas_treinamento

array([400000., 430000., 720000., ..., 431000., 411000., 699900.])

In [128]:
x_casas_teste

array([[1430],
       [4670],
       [1440],
       ...,
       [2150],
       [1480],
       [1320]], dtype=int64)

In [141]:
regressor_random_fores_casa=RandomForestRegressor(n_estimators=100)
regressor_random_fores_casa.fit(x_casas_treinamento,y_casas_treinamento)

RandomForestRegressor()

In [142]:
regressor_random_fores_casa.score(x_casas_treinamento,y_casas_treinamento)

0.6217824819514741

In [143]:
regressor_random_fores_casa.score(x_casas_teste,y_casas_teste)

0.5024924605716876

In [144]:
previsoes=regressor_random_fores_casa.predict(x_casas_teste)
previsoes

array([ 371666.07326143, 1193015.86428571,  366167.04187073, ...,
        506695.66455348,  430471.69537683,  369222.27889706])

In [145]:
y_casas_teste

array([ 297000., 1578000.,  562100., ...,  380000.,  268000.,  206000.])

In [147]:
mean_absolute_error(y_casas_teste,previsoes)

168952.4008967596

# **SVM**

In [148]:
x_plano_saude2

array([[18],
       [23],
       [28],
       [33],
       [38],
       [43],
       [48],
       [53],
       [58],
       [63]], dtype=int64)

In [149]:
y_plano_saude2

array([  470,   520,   630,   830,  1150,  1530,  2040,  3080,  5100,
       10100], dtype=int64)

# Kernel Linear 

In [150]:
from sklearn.svm import SVR
regressor_svr_saude=SVR(kernel='linear')
regressor_svr_saude.fit(x_plano_saude2,y_plano_saude2)

SVR(kernel='linear')

In [151]:

grafico2 = px.scatter(x=x_plano_saude2.ravel(), y=y_plano_saude2)
grafico2 . add_scatter(x=x_plano_saude2.ravel(
), y=regressor_svr_saude.predict(x_plano_saude2), name='Regressão')
grafico2.show()

# kERNEL POLINOMIAL

In [158]:

regressor_svr_saude_poly = SVR(kernel='poly',degree=4)
regressor_svr_saude_poly.fit(x_plano_saude2, y_plano_saude2)

SVR(degree=4, kernel='poly')

In [159]:

grafico2 = px.scatter(x=x_plano_saude2.ravel(), y=y_plano_saude2)
grafico2 . add_scatter(x=x_plano_saude2.ravel(
), y=regressor_svr_saude_poly.predict(x_plano_saude2), name='Regressão')
grafico2.show()

In [165]:
from sklearn.preprocessing import StandardScaler
scarle_x=StandardScaler()
x_plano_saude2_scarle=scarle_x.fit_transform(x_plano_saude2)
scarle_y=StandardScaler()
y_plano_saude2_scarle=scarle_y.fit_transform(y_plano_saude2.reshape(-1,1))


In [166]:
x_plano_saude2_scarle

array([[-1.5666989 ],
       [-1.21854359],
       [-0.87038828],
       [-0.52223297],
       [-0.17407766],
       [ 0.17407766],
       [ 0.52223297],
       [ 0.87038828],
       [ 1.21854359],
       [ 1.5666989 ]])

In [167]:
y_plano_saude2_scarle

array([[-0.72401136],
       [-0.7065653 ],
       [-0.66818397],
       [-0.59839975],
       [-0.48674498],
       [-0.35415495],
       [-0.17620517],
       [ 0.18667281],
       [ 0.8914935 ],
       [ 2.63609918]])

# Kernel rbf

In [170]:

regressor_svr_saude_rbf = SVR(kernel='rbf', )
regressor_svr_saude_rbf.fit(x_plano_saude2_scarle, y_plano_saude2_scarle.ravel())

SVR()

In [171]:

grafico2 = px.scatter(x=x_plano_saude2_scarle.ravel(), y=y_plano_saude2_scarle.ravel())
grafico2 . add_scatter(x=x_plano_saude2_scarle.ravel(
), y=regressor_svr_saude_rbf.predict(x_plano_saude2_scarle), name='Regressão')
grafico2.show()

In [190]:
novo=[[40]]


In [191]:
novo=scarle_x.transform(novo)
novo


array([[-0.03481553]])

In [ ]:
novo = novo.reshape(1, -1)
resultado = scarle_y.inverse_transform(regressor_svr_saude_rbf.predict(novo))

# Base preço das casas

In [193]:
x_casas_treinamento.shape,y_casas_treinamento.shape

((15129, 1), (15129,))

In [195]:
x_casas_teste.shape,y_casas_treinamento.shape

((6484, 1), (15129,))

In [210]:
from sklearn.preprocessing import StandardScaler
scarle_x_casas=StandardScaler()
x_casas_treinament_scaled=scarle_x_casas.fit_transform(x_casas_treinamento)
scarle_y_casas=StandardScaler()
y_casas_treinament_scaled=scarle_y_casas.fit_transform(y_casas_treinamento.reshape(-1,1))


In [211]:
x_casas_treinament_scaled

array([[-0.74522967],
       [-0.68028398],
       [ 0.84593978],
       ...,
       [ 0.30472568],
       [ 0.31554996],
       [ 0.32637425]])

In [212]:
y_casas_treinament_scaled

array([[-0.38454326],
       [-0.3024967 ],
       [ 0.49062008],
       ...,
       [-0.29976181],
       [-0.35445952],
       [ 0.43564888]])

In [213]:
x_casas_teste_scaled=scarle_x_casas.transform(x_casas_teste)
y_casas_teste_scaled=scarle_y_casas.transform(y_casas_teste.reshape(-1,1))

In [214]:
x_casas_teste_scaled

array([[-0.70193254],
       [ 2.80513482],
       [-0.69110826],
       ...,
       [ 0.07741576],
       [-0.64781113],
       [-0.82099964]])

In [206]:
y_casas_teste_scaled

array([[-0.65279094],
       [ 2.80442566],
       [ 0.06267207],
       ...,
       [-0.42878706],
       [-0.73105736],
       [-0.89838556]])

In [215]:
regressor_svr_casas=SVR(kernel='rbf')
regressor_svr_casas.fit(x_casas_treinament_scaled,y_casas_treinament_scaled.ravel())


SVR()

In [217]:
regressor_svr_casas.score(x_casas_treinament_scaled,y_casas_treinament_scaled)

0.5117557692887834

In [218]:
regressor_svr_casas.score(x_casas_teste_scaled, y_casas_teste_scaled)

0.48244979413787625

In [219]:
previsoes=regressor_svr_casas.predict(x_casas_teste_scaled)
previsoes

array([-0.46934709,  2.22606739, -0.46597917, ..., -0.16944439,
       -0.45270264, -0.50819424])

In [220]:
y_casas_teste_scaled

array([[-0.66623646],
       [ 2.83715179],
       [ 0.05878167],
       ...,
       [-0.43924097],
       [-0.74554814],
       [-0.91511104]])

In [221]:
mean_absolute_error(y_casas_teste_scaled,previsoes)

0.44596009082437704

# regressão com rede neurais artificiais 

In [222]:
x_plano_saude2_scarle

array([[-1.5666989 ],
       [-1.21854359],
       [-0.87038828],
       [-0.52223297],
       [-0.17407766],
       [ 0.17407766],
       [ 0.52223297],
       [ 0.87038828],
       [ 1.21854359],
       [ 1.5666989 ]])

In [223]:
y_plano_saude2_scarle

array([[-0.72401136],
       [-0.7065653 ],
       [-0.66818397],
       [-0.59839975],
       [-0.48674498],
       [-0.35415495],
       [-0.17620517],
       [ 0.18667281],
       [ 0.8914935 ],
       [ 2.63609918]])

In [226]:
from sklearn.neural_network import MLPRegressor
regressor_neural_saude=MLPRegressor(max_iter=1000)
regressor_neural_saude.fit(x_plano_saude2_scarle,y_plano_saude2_scarle.ravel())

MLPRegressor(max_iter=1000)

In [227]:
regressor_neural_saude.score(x_plano_saude2_scarle,y_plano_saude2_scarle)

0.9583586277410898

In [228]:

grafico2 = px.scatter(x=x_plano_saude2_scarle.ravel(),
                      y=y_plano_saude2_scarle.ravel())
grafico2 . add_scatter(x=x_plano_saude2_scarle.ravel(
), y=regressor_neural_saude.predict(x_plano_saude2_scarle), name='Regressão')
grafico2.show()

In [240]:
novo=[[40]]
novo=scarle_x.transform(novo)
novo.reshape(1,-1)


array([[-0.03481553]])

In [248]:
regressor_neural_saude.predict(novo)

array([-0.49515466])

# BASE PREÇO NAS CASASS

In [250]:
x_casas_treinament_scaled.shape

(15129, 1)

In [251]:
x_casas_treinament_scaled

array([[-0.74522967],
       [-0.68028398],
       [ 0.84593978],
       ...,
       [ 0.30472568],
       [ 0.31554996],
       [ 0.32637425]])

In [252]:
y_casas_treinament_scaled

array([[-0.38454326],
       [-0.3024967 ],
       [ 0.49062008],
       ...,
       [-0.29976181],
       [-0.35445952],
       [ 0.43564888]])

In [253]:
x_casas_teste_scaled.shape

(6484, 1)

In [255]:
#calculo neuronio
(1+1) /2

1.0

In [259]:
from sklearn.neural_network import MLPRegressor
regressor_neural_casa=MLPRegressor(max_iter=1000,  hidden_layer_sizes=(9,9))
regressor_neural_casa.fit(x_casas_treinament_scaled,y_casas_treinament_scaled.ravel())

MLPRegressor(hidden_layer_sizes=(9, 9), max_iter=1000)

In [260]:
regressor_neural_casa.score(x_casas_treinament_scaled,y_casas_treinament_scaled)

0.5372273685917077

In [261]:
regressor_neural_casa.score(x_casas_teste_scaled, y_casas_teste_scaled)

0.5376797361083205

In [262]:
previsoes=regressor_neural_casa.predict(x_casas_teste_scaled)
previsoes

array([-0.41835237,  2.43774591, -0.4141616 , ..., -0.08430319,
       -0.39627139, -0.46445087])

In [263]:
y_casas_teste_scaled

array([[-0.66623646],
       [ 2.83715179],
       [ 0.05878167],
       ...,
       [-0.43924097],
       [-0.74554814],
       [-0.91511104]])

In [ ]:
y_casas_teste_inverse=scarle_y_casas.inverse_transform(y_casas_teste_scaled)
previsoes_inverse=scarle_x_casas.inverse_transform(previsoes)

In [265]:
y_casas_teste_inverse

array([[ 297000.],
       [1578000.],
       [ 562100.],
       ...,
       [ 380000.],
       [ 268000.],
       [ 206000.]])

In [ ]:
previsoes_inverse

In [268]:
mean_absolute_error(y_casas_teste_scaled, previsoes)

0.4522260769292677