# Regressão linear simples

# **Base plano de saude**


In [2]:
%pip install plotly  --upgrade

Note: you may need to restart the kernel to use updated packages.


In [4]:
import plotly.express as px 
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [5]:
base_plano_de_saude=pd.read_csv('C:/Users/thale/Python/regressão parte2/plano_saude.csv')
base_plano_de_saude

idade  custo
0     18    871
1     23   1132
2     28   1242
3     33   1356
4     38   1488
5     43   1638
6     48   2130
7     53   2454
8     58   3066
9     63   4090

In [5]:
x_plano_saude=base_plano_de_saude.iloc[:, 0].values
x_plano_saude

array([18, 23, 28, 33, 38, 43, 48, 53, 58, 63], dtype=int64)

In [6]:
y_plano_saude=base_plano_de_saude.iloc[:,1].values
y_plano_saude

array([ 871, 1132, 1242, 1356, 1488, 1638, 2130, 2454, 3066, 4090],
      dtype=int64)

In [7]:
np.corrcoef(x_plano_saude,y_plano_saude)

array([[1.        , 0.93091958],
       [0.93091958, 1.        ]])

In [8]:
x_plano_saude.shape,y_plano_saude.shape

((10,), (10,))

In [10]:
x_plano_saude=x_plano_saude.reshape(-1,1)
x_plano_saude.shape

(10, 1)

In [11]:
from sklearn.linear_model import LinearRegression
regressor_plano_saude=LinearRegression()
regressor_plano_saude.fit(x_plano_saude,y_plano_saude)

LinearRegression()

In [12]:
regressor_plano_saude.intercept_

-558.9490909090912

In [13]:
regressor_plano_saude.coef_

array([61.86787879])

In [14]:
previsão=regressor_plano_saude.predict(x_plano_saude)
previsão

array([ 554.67272727,  864.01212121, 1173.35151515, 1482.69090909,
       1792.03030303, 2101.36969697, 2410.70909091, 2720.04848485,
       3029.38787879, 3338.72727273])

In [17]:
x_plano_saude.ravel()

array([18, 23, 28, 33, 38, 43, 48, 53, 58, 63], dtype=int64)

In [23]:
grafico=px.scatter(x=x_plano_saude.ravel(),y=y_plano_saude)
grafico.add_scatter(x=x_plano_saude.ravel(),y=previsão,name='Reressão')
grafico.show()

In [25]:
regressor_plano_saude.intercept_ +regressor_plano_saude.coef_ *40

array([1915.76606061])

In [28]:
regressor_plano_saude.predict([[40]])

array([1915.76606061])

In [29]:
regressor_plano_saude.score(x_plano_saude,y_plano_saude)

0.8666112727879174

In [3]:
from yellowbrick.regressor import ResidualsPlot
visualizador=ResidualsPlot(regressor_plano_saude)
visualizador.fit(x_plano_saude,y_plano_saude)
visualizador.poof()

NameError: name 'regressor_plano_saude' is not defined

# **BASE PREÇO DAS CASAS**

In [6]:
base_casas=pd.read_csv('C:/Users/thale/Python/regressão parte2/house_prices.csv')
base_casas

id             date     price  bedrooms  bathrooms  \
0      7129300520  20141013T000000  221900.0         3       1.00   
1      6414100192  20141209T000000  538000.0         3       2.25   
2      5631500400  20150225T000000  180000.0         2       1.00   
3      2487200875  20141209T000000  604000.0         4       3.00   
4      1954400510  20150218T000000  510000.0         3       2.00   
...           ...              ...       ...       ...        ...   
21608   263000018  20140521T000000  360000.0         3       2.50   
21609  6600060120  20150223T000000  400000.0         4       2.50   
21610  1523300141  20140623T000000  402101.0         2       0.75   
21611   291310100  20150116T000000  400000.0         3       2.50   
21612  1523300157  20141015T000000  325000.0         2       0.75   

       sqft_living  sqft_lot  floors  waterfront  view  ...  grade  \
0             1180      5650     1.0           0     0  ...      7   
1             2570      7242     2.0           0     0  ...      7   
2              770     10000     1.0           0     0  ...      6   
3             1960      5000     1.0           0     0  ...      7   
4             1680      8080     1.0           0     0  ...      8   
...            ...       ...     ...         ...   ...  ...    ...   
21608         1530      1131     3.0           0     0  ...      8   
21609         2310      5813     2.0           0     0  ...      8   
21610         1020      1350     2.0           0     0  ...      7   
21611         1600      2388     2.0           0     0  ...      8   
21612         1020      1076     2.0           0     0  ...      7   

       sqft_above  sqft_basement  yr_built  yr_renovated  zipcode      lat  \
0            1180              0      1955             0    98178  47.5112   
1            2170            400      1951          1991    98125  47.7210   
2             770              0      1933             0    98028  47.7379   
3            1050            910      1965             0    98136  47.5208   
4            1680              0      1987             0    98074  47.6168   
...           ...            ...       ...           ...      ...      ...   
21608        1530              0      2009             0    98103  47.6993   
21609        2310              0      2014             0    98146  47.5107   
21610        1020              0      2009             0    98144  47.5944   
21611        1600              0      2004             0    98027  47.5345   
21612        1020              0      2008             0    98144  47.5941   

          long  sqft_living15  sqft_lot15  
0     -122.257           1340        5650  
1     -122.319           1690        7639  
2     -122.233           2720        8062  
3     -122.393           1360        5000  
4     -122.045           1800        7503  
...        ...            ...         ...  
21608 -122.346           1530        1509  
21609 -122.362           1830        7200  
21610 -122.299           1020        2007  
21611 -122.069           1410        1287  
21612 -122.299           1020        1357  

[21613 rows x 21 columns]

In [7]:
base_casas.describe()

id         price      bedrooms     bathrooms   sqft_living  \
count  2.161300e+04  2.161300e+04  21613.000000  21613.000000  21613.000000   
mean   4.580302e+09  5.400881e+05      3.370842      2.114757   2079.899736   
std    2.876566e+09  3.671272e+05      0.930062      0.770163    918.440897   
min    1.000102e+06  7.500000e+04      0.000000      0.000000    290.000000   
25%    2.123049e+09  3.219500e+05      3.000000      1.750000   1427.000000   
50%    3.904930e+09  4.500000e+05      3.000000      2.250000   1910.000000   
75%    7.308900e+09  6.450000e+05      4.000000      2.500000   2550.000000   
max    9.900000e+09  7.700000e+06     33.000000      8.000000  13540.000000   

           sqft_lot        floors    waterfront          view     condition  \
count  2.161300e+04  21613.000000  21613.000000  21613.000000  21613.000000   
mean   1.510697e+04      1.494309      0.007542      0.234303      3.409430   
std    4.142051e+04      0.539989      0.086517      0.766318      0.650743   
min    5.200000e+02      1.000000      0.000000      0.000000      1.000000   
25%    5.040000e+03      1.000000      0.000000      0.000000      3.000000   
50%    7.618000e+03      1.500000      0.000000      0.000000      3.000000   
75%    1.068800e+04      2.000000      0.000000      0.000000      4.000000   
max    1.651359e+06      3.500000      1.000000      4.000000      5.000000   

              grade    sqft_above  sqft_basement      yr_built  yr_renovated  \
count  21613.000000  21613.000000   21613.000000  21613.000000  21613.000000   
mean       7.656873   1788.390691     291.509045   1971.005136     84.402258   
std        1.175459    828.090978     442.575043     29.373411    401.679240   
min        1.000000    290.000000       0.000000   1900.000000      0.000000   
25%        7.000000   1190.000000       0.000000   1951.000000      0.000000   
50%        7.000000   1560.000000       0.000000   1975.000000      0.000000   
75%        8.000000   2210.000000     560.000000   1997.000000      0.000000   
max       13.000000   9410.000000    4820.000000   2015.000000   2015.000000   

            zipcode           lat          long  sqft_living15     sqft_lot15  
count  21613.000000  21613.000000  21613.000000   21613.000000   21613.000000  
mean   98077.939805     47.560053   -122.213896    1986.552492   12768.455652  
std       53.505026      0.138564      0.140828     685.391304   27304.179631  
min    98001.000000     47.155900   -122.519000     399.000000     651.000000  
25%    98033.000000     47.471000   -122.328000    1490.000000    5100.000000  
50%    98065.000000     47.571800   -122.230000    1840.000000    7620.000000  
75%    98118.000000     47.678000   -122.125000    2360.000000   10083.000000  
max    98199.000000     47.777600   -121.315000    6210.000000  871200.000000

In [8]:
base_casas.isnull().sum()

id               0
date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
dtype: int64

In [9]:
x_casas=base_casas.iloc[:,5:6].values
x_casas

array([[1180],
       [2570],
       [ 770],
       ...,
       [1020],
       [1600],
       [1020]], dtype=int64)

In [10]:
y_casas=base_casas.iloc[:,2].values
y_casas

array([221900., 538000., 180000., ..., 402101., 400000., 325000.])

In [11]:
from sklearn.model_selection import train_test_split
x_casas_treinamento,x_casas_teste,y_casas_treinamento,y_casas_teste=train_test_split(x_casas,y_casas , test_size=0.3, random_state=0)

In [12]:
x_casas_treinamento.shape,y_casas_treinamento.shape

((15129, 1), (15129,))

In [13]:
x_casas_teste.shape,y_casas_teste.shape

((6484, 1), (6484,))

In [14]:
from sklearn.linear_model import LinearRegression

regressor_simples_casas=LinearRegression()
regressor_simples_casas.fit(x_casas_treinamento,y_casas_treinamento)

LinearRegression()

In [15]:
# Paramentro B0
regressor_simples_casas.intercept_

-37893.59850106761

In [16]:
# parametro B1
regressor_simples_casas.coef_

array([278.32860644])

In [17]:
regressor_simples_casas.score(x_casas_treinamento,y_casas_treinamento)

0.49453356717789776

In [18]:
regressor_simples_casas.score(x_casas_teste,y_casas_teste)

0.48889929019453027

In [19]:
previsoes=regressor_simples_casas.predict(x_casas_treinamento)
previsoes

array([348983.16445268, 365682.88083917, 758126.21592175, ...,
       618961.91270098, 621745.1987654 , 624528.48482981])

In [20]:
grafico=px.scatter(x=x_casas_treinamento.ravel(),y=previsoes)
grafico.show()

In [21]:

import plotly.graph_objects as go

grafico1=px.scatter(x=x_casas_treinamento.ravel(),y=y_casas_treinamento)
grafico2=px.line(x=x_casas_treinamento.ravel(),y=previsoes)
grafico2.data[0].line.color='red'
grafico3=go.Figure(data=grafico1.data + grafico2.data)
grafico3

In [22]:
previsoes_teste=regressor_simples_casas.predict(x_casas_teste)
previsoes_teste

array([ 360116.30871034, 1261900.99358095,  362899.59477476, ...,
        560512.90534826,  374032.73903242,  329500.16200177])

In [23]:
y_casas_teste

array([ 297000., 1578000.,  562100., ...,  380000.,  268000.,  206000.])

In [26]:
abs(y_casas_teste-previsoes_teste).mean()

172604.1288999542

In [27]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [30]:
mean_absolute_error(y_casas_teste,previsoes_teste)

172604.1288999542

In [29]:
mean_squared_error(y_casas_teste,previsoes_teste)

70170013932.1159

In [31]:
np.sqrt(mean_squared_error(y_casas_teste,previsoes_teste))

264896.23238565685

# Regressão linear Multipla

In [32]:
base_casas

id             date     price  bedrooms  bathrooms  \
0      7129300520  20141013T000000  221900.0         3       1.00   
1      6414100192  20141209T000000  538000.0         3       2.25   
2      5631500400  20150225T000000  180000.0         2       1.00   
3      2487200875  20141209T000000  604000.0         4       3.00   
4      1954400510  20150218T000000  510000.0         3       2.00   
...           ...              ...       ...       ...        ...   
21608   263000018  20140521T000000  360000.0         3       2.50   
21609  6600060120  20150223T000000  400000.0         4       2.50   
21610  1523300141  20140623T000000  402101.0         2       0.75   
21611   291310100  20150116T000000  400000.0         3       2.50   
21612  1523300157  20141015T000000  325000.0         2       0.75   

       sqft_living  sqft_lot  floors  waterfront  view  ...  grade  \
0             1180      5650     1.0           0     0  ...      7   
1             2570      7242     2.0           0     0  ...      7   
2              770     10000     1.0           0     0  ...      6   
3             1960      5000     1.0           0     0  ...      7   
4             1680      8080     1.0           0     0  ...      8   
...            ...       ...     ...         ...   ...  ...    ...   
21608         1530      1131     3.0           0     0  ...      8   
21609         2310      5813     2.0           0     0  ...      8   
21610         1020      1350     2.0           0     0  ...      7   
21611         1600      2388     2.0           0     0  ...      8   
21612         1020      1076     2.0           0     0  ...      7   

       sqft_above  sqft_basement  yr_built  yr_renovated  zipcode      lat  \
0            1180              0      1955             0    98178  47.5112   
1            2170            400      1951          1991    98125  47.7210   
2             770              0      1933             0    98028  47.7379   
3            1050            910      1965             0    98136  47.5208   
4            1680              0      1987             0    98074  47.6168   
...           ...            ...       ...           ...      ...      ...   
21608        1530              0      2009             0    98103  47.6993   
21609        2310              0      2014             0    98146  47.5107   
21610        1020              0      2009             0    98144  47.5944   
21611        1600              0      2004             0    98027  47.5345   
21612        1020              0      2008             0    98144  47.5941   

          long  sqft_living15  sqft_lot15  
0     -122.257           1340        5650  
1     -122.319           1690        7639  
2     -122.233           2720        8062  
3     -122.393           1360        5000  
4     -122.045           1800        7503  
...        ...            ...         ...  
21608 -122.346           1530        1509  
21609 -122.362           1830        7200  
21610 -122.299           1020        2007  
21611 -122.069           1410        1287  
21612 -122.299           1020        1357  

[21613 rows x 21 columns]

In [33]:
x_casas=base_casas.iloc[:,3:19].values
x_casas

array([[ 3.00000e+00,  1.00000e+00,  1.18000e+03, ...,  9.81780e+04,
         4.75112e+01, -1.22257e+02],
       [ 3.00000e+00,  2.25000e+00,  2.57000e+03, ...,  9.81250e+04,
         4.77210e+01, -1.22319e+02],
       [ 2.00000e+00,  1.00000e+00,  7.70000e+02, ...,  9.80280e+04,
         4.77379e+01, -1.22233e+02],
       ...,
       [ 2.00000e+00,  7.50000e-01,  1.02000e+03, ...,  9.81440e+04,
         4.75944e+01, -1.22299e+02],
       [ 3.00000e+00,  2.50000e+00,  1.60000e+03, ...,  9.80270e+04,
         4.75345e+01, -1.22069e+02],
       [ 2.00000e+00,  7.50000e-01,  1.02000e+03, ...,  9.81440e+04,
         4.75941e+01, -1.22299e+02]])

In [34]:
y_casas=base_casas.iloc[:,2].values
y_casas

array([221900., 538000., 180000., ..., 402101., 400000., 325000.])

In [35]:
from sklearn.model_selection import train_test_split
x_casas_treinamento,x_casas_teste,y_casas_treinamento,y_casas_teste = train_test_split(x_casas,y_casas , test_size=0.3, random_state=0)

In [36]:
x_casas_treinamento.shape,y_casas_treinamento.shape

((15129, 16), (15129,))

In [37]:
x_casas_teste.shape,y_casas_teste.shape

((6484, 16), (6484,))

In [38]:
regressor_multiplo_casas=LinearRegression()
regressor_multiplo_casas.fit(x_casas_treinamento,y_casas_treinamento)

LinearRegression()

In [39]:
regressor_multiplo_casas.intercept_

5736222.703393099

In [40]:
regressor_multiplo_casas.coef_

array([-3.08423090e+04,  3.66540816e+04,  1.12179159e+02,  8.00604120e-03,
        9.60355724e+03,  5.85441638e+05,  5.60621840e+04,  2.54795004e+04,
        1.01092121e+05,  6.96565318e+01,  4.25226264e+01, -2.60724691e+03,
        1.40070753e+01, -5.53557431e+02,  6.11778251e+05, -1.95564688e+05])

In [41]:
len(regressor_multiplo_casas.coef_)

16

In [42]:
regressor_multiplo_casas.score(x_casas_treinamento,y_casas_treinamento)

0.7029888085955006

In [43]:
regressor_multiplo_casas.score(x_casas_teste,y_casas_teste)

0.6885414149062383

In [45]:
previsoes=regressor_multiplo_casas.predict(x_casas_teste)
previsoes

array([ 383751.77768697, 1514216.17517442,  546921.96179118, ...,
        314968.57623284,  219405.55573558,  148128.83467052])

In [46]:
y_casas_teste

array([ 297000., 1578000.,  562100., ...,  380000.,  268000.,  206000.])

In [47]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_casas_teste,previsoes)

123888.44377484787